name: PR Test
on:
  pull_request:
    branches:
      - master
env:
  TURBO_DOCKER_TOKEN: ${{secrets.TURBO_DOCKER_TOKEN}}

jobs:
  test:
    name: Lint, Audit, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run Cypress E2E Tests
        run: |
          docker-compose up --exit-code-from cypress

      - name: Tear Down
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker rmi turbo-deploy-example_web
          docker rmi cypress/included:13.5.1
